version: '3.7'
services:
    gateway:
        restart: unless-stopped
        image: ${REGISTRY}/english-gateway:${IMAGE_TAG}
        ports:
            - 80:80
            - 443:443
        volumes:
          - ./running:/etc/letsencrypt/live/
          - /var/www/html:/var/www/html
        depends_on:
            - frontend-nginx
            - backend-nginx

    frontend-nginx:
        restart: unless-stopped
        image: ${REGISTRY}/english-frontend-nginx:${IMAGE_TAG}

    frontend-npm:
        image: ${REGISTRY}/english-frontend-npm:${IMAGE_TAG}
        tty: true
        restart: unless-stopped

    backend-nginx:
        restart: unless-stopped
        image: ${REGISTRY}/english-backend-nginx:${IMAGE_TAG}
        depends_on:
          - backend-php-fpm
          - backend-mysql

    backend-mysql:
        image: mysql:8.0
        restart: unless-stopped
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=user
            - MYSQL_PASSWORD=user
            - MYSQL_DATABASE=app
            - TZ=Europe/Moscow
        volumes:
            - ./running/mysql:/var/lib/mysql/

    backend-php-cli:
        image: ${REGISTRY}/english-backend-php-cli:${IMAGE_TAG}
        user: ${USER}
        tty: true

    backend-php-fpm:
        image: ${REGISTRY}/english-backend-php-fpm:${IMAGE_TAG}
        user: ${USER}
        volumes:
            - ./running/logs/:/var/www/docker/production/logs/
        restart: unless-stopped
        #        ports:
        #            - "9001:9001"

    backend-npm:
        image: ${REGISTRY}/english-backend-npm:${IMAGE_TAG}
        tty: true
        restart: unless-stopped

    backend-redis:
        image: redis


