version: '3.7'
services:
    gateway:
        restart: unless-stopped
        image: ${REGISTRY}/english-gateway:${IMAGE_TAG}
        ports:
            - 80:80
            - 443:443
        volumes:
          - /etc/letsencrypt/:/etc/letsencrypt/
          - /var/www/html:/var/www/html
          - ./running/logs/gateway:/var/log/nginx
        depends_on:
            - frontend-nginx
            - backend-nginx

    frontend-nginx:
        restart: unless-stopped
        image: ${REGISTRY}/english-frontend-nginx:${IMAGE_TAG}

    backend-nginx:
        restart: unless-stopped
        image: ${REGISTRY}/english-backend-nginx:${IMAGE_TAG}
        depends_on:
          - backend-php-fpm
          - backend-mysql

    backend-mysql:
        image: mysql:8.0
        restart: unless-stopped
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=user
            - MYSQL_PASSWORD=user
            - MYSQL_DATABASE=app
            - TZ=Europe/Moscow
        volumes:
            - ./running/mysql:/var/lib/mysql/

    backend-php-fpm:
        image: ${REGISTRY}/english-backend-php-fpm:${IMAGE_TAG}
        environment:
          - APP_URL=https://api.developer-nero.ru
          - DB_HOST=backend-mysql
          - DB_DATABASE=app
          - DB_USERNAME=root
          - DB_PASSWORD=root
          - CACHE_DRIVER=redis
          - QUEUE_CONNECTION=redis
          - SESSION_DRIVER=redis
          - REDIS_HOST=backend-redis
        volumes:
            - ./running/logs/laravel:/var/www/storage/logs
        restart: unless-stopped

    backend-redis:
        image: redis


