name: Testing workflow

on:
  push:
    branches:
      - v2

jobs:
  ci-backend:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Composer install
          uses: php-actions/composer@v6
          with:
            php_version: "8.1"
            args: -d backend

        - name: Run Psalm check
          run: backend/vendor/bin/psalm --no-cache -c backend/psalm.xml

        - name: Run PHP tests
          run: backend/vendor/bin/phpunit -c backend/phpunit.xml

  ci-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
            node-version: '18.13'

      - name: Install Dependencies
        run: npm install ./frontend

      - name: Eslint Check
        run: npx eslint frontend/src
