name: Testing workflow

on:
  push:
    branches:
      - v2

jobs:
  CI:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Composer install
          uses: php-actions/composer@v6
          with:
            php_version: "8.1"

        - name: Psalm check
          run: ./backend/vendor/bin/psalm --no--cache

#        - name: PHPUnit tests
#          run: ./backend/vendor/bin/phpunit

