name: Testing workflow

on:
  push:
    branches:
      - v2

jobs:
  ci-backend:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Composer install
          uses: php-actions/composer@v6
          with:
            php_version: "8.1"
            args: -d backend

        - name: Psalm check
          run: ./backend/vendor/bin/psalm --no-cache -c ./backend/psalm.xml

#        - name: PHPUnit tests
#          run: ./backend/vendor/bin/phpunit

