name: Testing workflow

on:
  push:
    branches:
      - v2

jobs:
  main:
      runs-on: ubuntu-latest
      steps:
        - name: Composer install
          uses: php-actions/composer@v6
          with:
            php_version: "8.0"

  test2:
      runs-on: ubuntu-latest
      steps:
        - name: Checking github
          run: echo {{ toJson(github) }}
          shell: bash
