name: Testing workflow

on:
  push:
    branches:
      - v2

jobs:
  CI:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Composer install
          uses: php-actions/composer@v6
          with:
            php_version: "8.0"

  test2:
      runs-on: ubuntu-latest
      steps:
        - name: Checking github
          run: echo "${{ toJSON(github) }}"
          shell: bash
